import React, { createContext, useContext, useState, ReactNode, useMemo } from "react";
import { CartItem } from "../shared/types";

interface CartContextType {
  items: CartItem[];
  addItem: (item: CartItem) => void;
  removeItem: (cartId: string) => void;
  updateQuantity: (cartId: string, quantity: number) => void;
  clearCart: () => void;
  total: number;
  itemCount: number;
}

const CartContext = createContext<CartContextType | undefined>(undefined);

export function CartProvider({ children }: { children: ReactNode }) {
  const [items, setItems] = useState<CartItem[]>([]);

  const addItem = (item: CartItem) => {
    setItems((prev) => {
      // Check if an identical item (same ID, same addons, same flavors) exists
      // For simplicity, we'll use cartId generated by the modal for now, 
      // but we could also merge items here.
      return [...prev, item];
    });
  };

  const removeItem = (cartId: string) => {
    setItems((prev) => prev.filter((i) => i.cartId !== cartId));
  };

  const updateQuantity = (cartId: string, quantity: number) => {
    setItems((prev) =>
      prev.map((i) => (i.cartId === cartId ? { ...i, quantidade: Math.max(0, quantity) } : i))
    );
  };

  const clearCart = () => setItems([]);

  const total = useMemo(() => 
    items.reduce((acc, item) => acc + item.precoFinal * item.quantidade, 0),
  [items]);

  const itemCount = useMemo(() => 
    items.reduce((acc, item) => acc + item.quantidade, 0),
  [items]);

  return (
    <CartContext.Provider value={{ items, addItem, removeItem, updateQuantity, clearCart, total, itemCount }}>
      {children}
    </CartContext.Provider>
  );
}

export function useCart() {
  const context = useContext(CartContext);
  if (context === undefined) {
    throw new Error("useCart must be used within a CartProvider");
  }
  return context;
}
